work/depot/config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  
  controller :sessions do
	get  'login' => :new
	post 'login' => :create
	delete 'logout' => :destroy
  end
  
  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products do
	get :who_bought, on: :member
  end
  
  resources :line_items do
    put 'decrement', on: :member
  end
  

  
  root 'store#index'
end

work/depot/app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
<!-- START_HIGHLIGHT -->
<title>Everything Store</title>
<!-- END_HIGHLIGHT -->
  <%= stylesheet_link_tag    "application", media: "all" %><!-- <label id="code.slt"/> -->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %><!-- <label id="code.csrf"/> -->
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">
<!-- START_HIGHLIGHT -->
  <div id="banner">
    <%= image_tag("logo.jpg") %>
    <%= @page_title || "Everything Store" %><!-- <label id="code.depot.e.title"/> -->
  </div>
  <div id="columns">
    <div id="side">
	  <% if @cart %>
		<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
			<%= render @cart %>
		<% end %>
	  <% end %>

      <ul>
        <li><a href=<%= store_index_url %>>Home</a></li>
        <li><a href="http://www..../faq">Questions</a></li>
        <li><a href="http://www..../news">News</a></li>
        <li><a href="http://www..../contact">Contact</a></li>
      </ul>
	  
	  <% if session[:user_id] %>
		<ul>
			<li><%= link_to 'Orders', orders_path %></li>
			<li><%= link_to 'Products', products_path %></li>
			<li><%= link_to 'Users', users_path %></li>
		</ul>
		<%= button_to 'Logout', logout_path, method: :delete %>
	  <% end %>
	  <p id=lastUpdated>Last updated <%= @time %></p>
    </div>
    <div id="main">
<!-- END_HIGHLIGHT -->
      <%= yield %><!-- <label id="code.depot.e.include"/> -->
<!-- START_HIGHLIGHT -->
    </div>
  </div>
<!-- END_HIGHLIGHT -->
</body>
</html>